on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch Credentials
        run: |
          echo "$KEY_FILE_PEM" > honeypot.pem
          chmod 400 honeypot.pem
          echo "$SECRETS_ENV_FILE" > secrets.env
        env:
          KEY_FILE_PEM: ${{ secrets.KEY_FILE_PEM }}
          SECRETS_ENV_FILE: ${{ secrets.SECRETS_ENV_FILE }}
      - name: Add Secrets to appsettings
        run: |
          echo "export ExcludedIPs=$EXCLUDED_IPS" >> appsettings.env
          echo "export AbuseIPDBKey=$ABUSE_IPDB_KEY" >> appsettings.env
        env:
          EXCLUDED_IPS: ${{ secrets.EXCLUDED_IPS }}
          ABUSE_IPDB_KEY: ${{ secrets.ABUSE_IPDB_KEY }}
      - name: Setup Go environment
        uses: actions/setup-go@v3.5.0
      - name: Deploy
        run: bash deploy.sh
        
    
